name: portfolio
description: A new Flutter project.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  font_awesome_flutter: ^9.1.0
  url_launcher: ^6.0.12
  http: ^0.13.4

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: FiraCode
      fonts:
        - asset: assets/fonts/FiraCode-Bold.ttf
        - asset: assets/fonts/FiraCode-Light.ttf
        - asset: assets/fonts/FiraCode-Medium.ttf
        - asset: assets/fonts/FiraCode-Regular.ttf
        - asset: assets/fonts/FiraCode-Retina.ttf
        - asset: assets/fonts/FiraCode-SemiBold.ttf
